project:
  type: website
  title: "Machine Learning with Python"
  preview: 
    port: 4600
  output-dir: _site
  resources:
    - "exercises/*.ipynb"
  brand: _brand.yml

bibliography: references.bib

execute:
  # https://quarto.org/docs/computations/python.html#kernel-daemon
  daemon: true 

  # https://quarto.org/docs/computations/caching.html#jupyter-cache
  cache: true

  # https://quarto.org/docs/publishing/github-pages.html#freezing-computations
  freeze: auto


dir: rtl
lang: ar
language: _language_ar.yml

format:
  html:
    theme: [cosmo, custom.scss]
  revealjs:
    theme: [default, custom.scss]
    slide-number: c/t
    show-slide-number: all
    transition: slide
    background-transition: fade
    chalkboard: true
    progress: true
    history: true
    scrollable: true
    rtl: true
    dir: rtl

number-depth: 1
lightbox: auto