---
title: "القيم المفقودة"
format: html
---

## المشكلة

تتطلب معظم خوارزميات المكتبة ألا تحتوي البيانات على فراغات.

وهناك أسباب كثيرة تؤدي لفقدان البيانات في كثير من الأحيان، منها:

- **خطأ طبيعي:** إغفال الإدخال سهواً أو تعمد المستخدم عدم الإجابة لحماية خصوصيته.
- **عطل تقني:** خلل في الحساسات أو انقطاع الاتصال أثناء نقل البيانات.
- **دمج البيانات:** فجوات ناتجة عن عمليات الربط (SQL Joins) أو تغير هيكلة الجداول عبر الزمن.
- **الانسحاب:** فقدان البيانات بسبب انسحاب المشاركين من الدراسة المرحلية أو حذف الحسابات.
  - مثال: في التجارب الطبية، قد ينسحب المريض بسبب الهجرة، الوفاة، أو ببساطة الملل من المتابعة، أو لأن حالته ساءت أو لأنه عانى من أعراض جانبية حادة.
  - مثال: في الأنظمة التي تعتمد على الاشتراكات، هم العملاء الذين توقفوا عن استخدام الخدمة. تظهر بياناتهم فارغة في الأشهر التي تلت توقفهم.

## طريقة الحل

لو تصوَّرنا البيانات في جدوَل، فإن الحل البسيط قد يكون بإزالة تلك الصفوف ذات القيَم المفقودة. لكن ذلك يؤدي لخسارة المعلومات الأخرى الموجودة في نفس الصف. والأفضل أن نقوم **باستكمال** (Impute) القيم المفقودة، أي: استنتاجها من الجزء المعلوم من البيانات.

واستنتاجُها يكون بأحد طريقين:

الأول: **من القيَم الأخرى لنفس المتغيِّر** ([`SimpleImputer`](https://scikit-learn.org/stable/modules/impute.html#univariate-feature-imputation)). كحساب المتوسط أو الوسيط أو الأكثر تكرارًا أو قيمة ثابتة.

الثاني: **باعتبار المتغيرات الأخرى** ([مثل: `IterativeImputer`](https://scikit-learn.org/stable/modules/impute.html#multivariate-feature-imputation)). ويكون بذلك مسألة تنبؤ: انحدار (Regression) أو تصنيف (Classification) بحسب نوع المتغيِّر ذي القيمة المفقودة.

- بيانات تجريبية تحتوي على قيم مفقودة (NaN)

```python
import numpy as np
X = [[1, 2, np.nan], 
     [3, 4, 3], 
     [np.nan, 6, 5], 
     [8, 8, 7]]

```

- التقدير البسيط (Mean)

```python
from sklearn.impute import SimpleImputer

mean_imputer = SimpleImputer(strategy='mean')
X_transformed = mean_imputer.fit_transform(X)
X_transformed
```

- التقدير باستخدام خوارزمية التعلم: **أقرب الجيران (KNN)**:

```python
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(n_neighbors=2)
X_transformed = knn_imputer.fit_transform(X)
X_transformed
```

---

انظر: [ملء القيم المفقودة](https://scikit-learn.org/stable/modules/impute.html).